### ISSUE TITLE
Why LedgerDB implementation use only 1 blocks per transaction?

### ISSUE THREAD

**Issue by TKONIY** [nusdbsystem/LedgerDatabase#1]
I observed that the for YCSB workload, each transaction generates one block. In my understanding, it can hurts the performance by incurring more RocksDB callings.

**Comment by yc1111** [comment]
<img width="484" alt="image" src="https://github.com/nusdbsystem/LedgerDatabase/assets/1707974/f6e8ca24-4ec9-4a8e-ae40-c38093013c25">

For LedgerDB, we are following the architecture in the original paper as shown in the figure. However, the "blocks" in our code refer to the leaf nodes of the Merkle tree (the nodes with H0, H1, H2 ...). We use "commits" to refer to the blocks in the original paper(Block0, Block1, Block2 ...). One "block" contains only one transaction, and one "commit" can collect multiple transactions within a timeout set by the user.

Hope this could answer your question.

**Comment by TKONIY** [comment]
Thanks very much for the response. The figure is quite clear, about the relation between "blocks" and "transactions". You are very nice!

But I still have a problem with "commit". In your code, one ["commit"](https://github.com/nusdbsystem/LedgerDatabase/blob/61534e568d19fd0bfebe269ad4615c1f1b6fff6f/distributed/store/strongstore/occstore.cc#L80C1-L80C1) contains only one transaction, instead of multiple transactions. Key-values of multiple transactions are collected into `tree_queue_` and processed by [`buildTree`](https://github.com/nusdbsystem/LedgerDatabase/blob/61534e568d19fd0bfebe269ad4615c1f1b6fff6f/ledger/ledgerdb/ledgerdb.cc#L39C13-L39C13) thread in the background. 

Is there anything that I get wrong?

**Comment by yc1111** [comment]
buildTree will pop all blocks in tree_queue_, which are collected during a period of time, and update the Merkle tree and MPT. After that, the commit entry will be created as follows

```
std::string commit_entry = CommitInfo(commit_seq_, prev_digest,
          last_block, root_hash, root_key, newmptroot.ToBase32()).ToString();
```

Therefore, one commit contains multiple transactions.

**Comment by TKONIY** [comment]
Thank you!
